{{- range .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
{{- if .sources }}
  sources:
    {{- toYaml .sources | nindent 4 }}
{{- else }}
  source:
    repoURL: {{ .repoURL }}
    targetRevision: HEAD
    path: {{ .path }}
{{- if .directory }}
    directory:
      {{- toYaml .directory | nindent 6 }}
{{- end }}
{{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
{{- if .ignoreDifferences }}
  ignoreDifferences:
    {{- toYaml .ignoreDifferences | nindent 4 }}
{{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- if not (hasKey . "retry") }}
    retry:
      limit: {{ $.Values.retryDefaults.limit }}
      backoff:
        duration: {{ $.Values.retryDefaults.backoff.duration }}
        factor: {{ $.Values.retryDefaults.backoff.factor }}
        maxDuration: {{ $.Values.retryDefaults.backoff.maxDuration }}
{{- end }}
{{- if .syncOptions }}
    syncOptions:
      {{- toYaml .syncOptions | nindent 6 }}
{{- end }}
{{- end }}
